/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, GNU /usr/bin/c++ 13.3.0) */

module adder(a, b, cin, sum, cout);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  input cin;
  wire cin;
  output [15:0] sum;
  wire [15:0] sum;
  output cout;
  wire cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  sky130_fd_sc_hd__nand2_1 _051_ (
    .A(a[15]),
    .B(b[15]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _052_ (
    .A(a[15]),
    .B(b[15]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and2_0 _053_ (
    .A(a[14]),
    .B(b[14]),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _054_ (
    .A(a[14]),
    .B(b[14]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _055_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _056_ (
    .A(a[13]),
    .B(b[13]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _057_ (
    .A(a[13]),
    .SLEEP(b[13]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _058_ (
    .A(a[12]),
    .B(b[12]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _059_ (
    .A(a[12]),
    .B(b[12]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__and2_0 _060_ (
    .A(a[11]),
    .B(b[11]),
    .X(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _061_ (
    .A(a[11]),
    .B(b[11]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and2_0 _062_ (
    .A(a[10]),
    .B(b[10]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _063_ (
    .A(a[8]),
    .B(b[8]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _064_ (
    .A(a[8]),
    .B(b[8]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and2_0 _065_ (
    .A(a[7]),
    .B(b[7]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _066_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__and2_0 _067_ (
    .A(a[6]),
    .B(b[6]),
    .X(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _068_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__maj3_1 _069_ (
    .A(a[0]),
    .B(b[0]),
    .C(cin),
    .X(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _070_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__maj3_1 _071_ (
    .A(a[1]),
    .B(b[1]),
    .C(_022_),
    .X(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _072_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__maj3_1 _073_ (
    .A(a[2]),
    .B(b[2]),
    .C(_024_),
    .X(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _074_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__maj3_1 _075_ (
    .A(a[3]),
    .B(b[3]),
    .C(_026_),
    .X(_028_)
  );
  sky130_fd_sc_hd__xnor2_1 _076_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__maj3_1 _077_ (
    .A(a[4]),
    .B(b[4]),
    .C(_028_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _078_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__maj3_1 _079_ (
    .A(a[5]),
    .B(b[5]),
    .C(_030_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _081_ (
    .A(_020_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a21o_1 _082_ (
    .A1(_032_),
    .A2(_034_),
    .B1(_020_),
    .X(_035_)
  );
  sky130_fd_sc_hd__a211oi_1 _083_ (
    .A1(_032_),
    .A2(_034_),
    .B1(_018_),
    .C1(_020_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _084_ (
    .A(_019_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__o31ai_1 _085_ (
    .A1(_017_),
    .A2(_019_),
    .A3(_036_),
    .B1(_016_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _086_ (
    .A(a[9]),
    .B(b[9]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__maj3_1 _087_ (
    .A(a[9]),
    .B(b[9]),
    .C(_038_),
    .X(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _088_ (
    .A(a[10]),
    .B(b[10]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(_015_),
    .B(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a21oi_1 _090_ (
    .A1(_040_),
    .A2(_042_),
    .B1(_015_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a211oi_1 _091_ (
    .A1(_040_),
    .A2(_042_),
    .B1(_013_),
    .C1(_015_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _092_ (
    .A(_014_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o31ai_1 _093_ (
    .A1(_012_),
    .A2(_014_),
    .A3(_044_),
    .B1(_011_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o311ai_0 _094_ (
    .A1(_012_),
    .A2(_014_),
    .A3(_044_),
    .B1(_011_),
    .C1(_009_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand3_1 _095_ (
    .A(_008_),
    .B(_010_),
    .C(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a31oi_1 _096_ (
    .A1(_008_),
    .A2(_010_),
    .A3(_047_),
    .B1(_006_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _097_ (
    .A1(_004_),
    .A2(_049_),
    .B1(_005_),
    .Y(cout)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(_004_),
    .SLEEP(_005_),
    .X(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _099_ (
    .A(_049_),
    .B(_050_),
    .Y(sum[15])
  );
  sky130_fd_sc_hd__a21oi_1 _100_ (
    .A1(_010_),
    .A2(_047_),
    .B1(_008_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _101_ (
    .A(_048_),
    .SLEEP(_000_),
    .X(sum[14])
  );
  sky130_fd_sc_hd__nand2_1 _102_ (
    .A(_009_),
    .B(_010_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _103_ (
    .A(_046_),
    .B(_001_),
    .Y(sum[13])
  );
  sky130_fd_sc_hd__xnor2_1 _104_ (
    .A(_012_),
    .B(_045_),
    .Y(sum[12])
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(_013_),
    .B(_014_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xnor2_1 _106_ (
    .A(_043_),
    .B(_002_),
    .Y(sum[11])
  );
  sky130_fd_sc_hd__xor2_1 _107_ (
    .A(_040_),
    .B(_042_),
    .X(sum[10])
  );
  sky130_fd_sc_hd__xnor2_1 _108_ (
    .A(_038_),
    .B(_039_),
    .Y(sum[9])
  );
  sky130_fd_sc_hd__xnor2_1 _109_ (
    .A(_017_),
    .B(_037_),
    .Y(sum[8])
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(_018_),
    .B(_019_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xor2_1 _111_ (
    .A(_035_),
    .B(_003_),
    .X(sum[7])
  );
  sky130_fd_sc_hd__xor2_1 _112_ (
    .A(_032_),
    .B(_034_),
    .X(sum[6])
  );
  sky130_fd_sc_hd__xnor2_1 _113_ (
    .A(_030_),
    .B(_031_),
    .Y(sum[5])
  );
  sky130_fd_sc_hd__xnor2_1 _114_ (
    .A(_028_),
    .B(_029_),
    .Y(sum[4])
  );
  sky130_fd_sc_hd__xnor2_1 _115_ (
    .A(_026_),
    .B(_027_),
    .Y(sum[3])
  );
  sky130_fd_sc_hd__xnor2_1 _116_ (
    .A(_024_),
    .B(_025_),
    .Y(sum[2])
  );
  sky130_fd_sc_hd__xnor2_1 _117_ (
    .A(_022_),
    .B(_023_),
    .Y(sum[1])
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(cin),
    .B(_021_),
    .Y(sum[0])
  );
endmodule
