/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, GNU /usr/bin/c++ 13.3.0) */

module adder(a, b, cin, sum, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input cin;
  wire cin;
  output [7:0] sum;
  wire [7:0] sum;
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _22_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and2_0 _23_ (
    .A(a[5]),
    .B(b[5]),
    .X(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and2_0 _25_ (
    .A(a[4]),
    .B(b[4]),
    .X(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__maj3_1 _27_ (
    .A(a[0]),
    .B(b[0]),
    .C(cin),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__maj3_1 _29_ (
    .A(a[1]),
    .B(b[1]),
    .C(_06_),
    .X(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__maj3_1 _31_ (
    .A(a[2]),
    .B(b[2]),
    .C(_08_),
    .X(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__maj3_1 _33_ (
    .A(a[3]),
    .B(b[3]),
    .C(_10_),
    .X(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _35_ (
    .A(_04_),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a21o_1 _36_ (
    .A1(_12_),
    .A2(_14_),
    .B1(_04_),
    .X(_15_)
  );
  sky130_fd_sc_hd__a211oi_1 _37_ (
    .A1(_12_),
    .A2(_14_),
    .B1(_02_),
    .C1(_04_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor2_1 _38_ (
    .A(_03_),
    .B(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o31ai_1 _39_ (
    .A1(_01_),
    .A2(_03_),
    .A3(_16_),
    .B1(_00_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(a[7]),
    .B(b[7]),
    .C(_18_),
    .X(cout)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_18_),
    .B(_19_),
    .Y(sum[7])
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_01_),
    .B(_17_),
    .Y(sum[6])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _44_ (
    .A(_02_),
    .SLEEP(_03_),
    .X(_20_)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_15_),
    .B(_20_),
    .Y(sum[5])
  );
  sky130_fd_sc_hd__xor2_1 _46_ (
    .A(_12_),
    .B(_14_),
    .X(sum[4])
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_10_),
    .B(_11_),
    .Y(sum[3])
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(_08_),
    .B(_09_),
    .Y(sum[2])
  );
  sky130_fd_sc_hd__xnor2_1 _49_ (
    .A(_06_),
    .B(_07_),
    .Y(sum[1])
  );
  sky130_fd_sc_hd__xnor2_1 _50_ (
    .A(cin),
    .B(_05_),
    .Y(sum[0])
  );
endmodule
