/* Generated by Yosys 0.68 (git sha1 38e001a6f, Release, GNU /usr/bin/c++ 13.3.0) */

module counter(clk, rst, en, count, wrap);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output [3:0] count;
  wire [3:0] count;
  output wrap;
  wire wrap;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__and4_1 _11_ (
    .A(count[1]),
    .B(count[2]),
    .C(count[3]),
    .D(count[0]),
    .X(wrap)
  );
  sky130_fd_sc_hd__o21ai_0 _12_ (
    .A1(en),
    .A2(count[0]),
    .B1(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a21oi_1 _13_ (
    .A1(en),
    .A2(count[0]),
    .B1(_05_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand4_1 _14_ (
    .A(count[1]),
    .B(en),
    .C(count[2]),
    .D(count[0]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xor2_1 _15_ (
    .A(count[3]),
    .B(_06_),
    .X(_07_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(rst),
    .B(_07_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _17_ (
    .A(count[1]),
    .B(en),
    .C(count[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__o211a_1 _18_ (
    .A1(count[2]),
    .A2(_08_),
    .B1(_06_),
    .C1(_04_),
    .X(_02_)
  );
  sky130_fd_sc_hd__a21oi_1 _19_ (
    .A1(en),
    .A2(count[0]),
    .B1(count[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor3_1 _20_ (
    .A(rst),
    .B(_08_),
    .C(_09_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _24_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[3])
  );
endmodule
